wordpress:
  build: .
  # image: framallo/php-fpm
  links:
    - db:mysql
  ports:
    - 8080:80
  environment:
    DB_NAME: wordpress_development
    DB_USER: root
    DB_PASS: 12345Abc
    #VERBOSE_TEMPLATES: true
    #WP_RELOCATE: false
    #WP_HOME: "WP_HOME"
    #WP_SITEURL: "WP_SITEURL"
      

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 12345Abc

